language: node_js
node_js: 12
cache:
  directories:
    - node_modules
script:
  - npm run build
  - npm test
env:
  global:
    - GCP_ENV=$(if [[ "$TRAVIS_BRANCH" = "master" ]]; then echo "prod"; else if [[ "$TRAVIS_BRANCH" = "qa" ]]; then echo "qa"; else echo "dev"; fi; fi)
    - GCP_PROJECT_ID=$(echo "${GCP_ENV}_project_id")
notifications:
  email: false
  slack:
    rooms: bpsmart:cOFxwweHbT66YDbMwzgUaCZJ
    template:
      - 'Build <%{build_url}|#%{build_number}> (<%{compare_url}|%{commit}: ''%{commit_subject}''>)  by
      %{author} for %{repository_name}@%{branch}, %{result} in %{duration}. <%{build_url}|Check
      details>.'
before_install:
  - openssl aes-256-cbc -K $encrypted_0a7c5220d0a3_key -iv $encrypted_0a7c5220d0a3_iv
    -in ./deploy/ci-sec.tar.enc -out ./deploy/ci-sec.tar -d
  - tar xvf ./deploy/ci-sec.tar -C ./deploy/ &>/dev/null
before_script:
  - chmod +x ./deploy/*.sh
  - ./deploy/pre_deploy.sh
deploy:
  provider: gae
  keyfile: $(echo "./deploy/travisci-bpsmart-${GCP_ENV}-service.json")
  project: $(echo "${!GCP_PROJECT_ID}")
  skip_cleanup: true
  on:
    all_branches: true
    condition: '"$(./deploy/can_deploy.sh $TRAVIS_BRANCH $TRAVIS_COMMIT_MESSAGE)" == "1"'
